# Tipos de variables

Una variable es un espacio de memoria reservado para guardar información que puede cambiar.
Tipos básicos de variables:
Números enteros (int)
Números reales (decimales) (float)
cadenas de texto (str)
booleanos (bol)

## Números enteros: int

In [133]:
numRepeticiones=4
print(numRepeticiones)

4


## Números reales, que incluyen los decimales: float

In [134]:
talla=1.89
print(talla)

1.89


## Cadenas de texto: str

In [135]:
saludo='hola'
despedida="adios"

También se puede operar con las variables de texto

In [136]:
texto= saludo+ ' y después '+ despedida
print(texto)

hola y después adios


Se puede dar formato al texto cuando se integran números (decimales, etc.)

In [137]:
decimal= 1.3948576647485
entero=4
texto='número'

resultado = '{:s} decimal = {:.3f}, el entero = {:00d}'.format(texto, decimal, entero)
print(resultado)

número decimal = 1.395, el entero = 4


## Número booleanos (bool)

Solo admiten como valor True o False

In [138]:
a=True
b=False
c=True

Se pueden transformar de unos tipos a otros:

In [139]:
a=5.6#float
b=int(a)
print(a, b)

5.6 5


In [140]:
a=3#int
b=float(a)
print(a, b)

3 3.0


In [141]:
a='5'
b=int(a)
print(a, b)
print(5*a)#no multiplica sino que lo repite porque es una cadena de texto
print(5*b)#realiza la operación matemática porque es un número

5 5
55555
25


In [142]:
a=5
b=str(a)
print(a, b)
print(5*a)#al revés que el anterior
print(5*b)

5 5
25
55555


## Listas

Hasta ahora cada variable almacena un solo dato.
Si necesitamos manejar muchos datos es inviable. Ej. registro de tiempos de vuelo en saltos:

In [143]:
tv1=0.476
tv2=0.381
tv3=0.534

En python se pueden crear listas de datos separándolos con comas:

In [144]:
tv=[0.476, 0.381, 0.534]

Las listas pueden contener cualquier tipo de datos:

In [145]:
AlturaSalto=['Sujeto1', 0.23, 'Sujeto2', 0.38, 'Sujeto3', 0.15]
print(AlturaSalto)

['Sujeto1', 0.23, 'Sujeto2', 0.38, 'Sujeto3', 0.15]


 Se puede acceder a cada elemento de la lista. ATENCIÓN, el indexado empieza en 0:

In [146]:
print(AlturaSalto[0], AlturaSalto[2])

Sujeto1 Sujeto2


In [147]:
print(AlturaSalto[-1])#el último elemento
print(AlturaSalto[-2])#el penúltimo elemento

0.15
Sujeto3


Una característica interesante es que se puede acceder a varios elementos de una vez.

In [148]:
print(AlturaSalto[2:4])#no incluye el último elemento indicado

['Sujeto2', 0.38]


In [149]:
print(AlturaSalto[:3])#si se deja en blanco antes de : indica desde el principio

['Sujeto1', 0.23, 'Sujeto2']


In [150]:
print(AlturaSalto[3:])#si se deja en blanco después de : indica hasta el final

[0.38, 'Sujeto3', 0.15]


In [151]:
print(AlturaSalto[:-1]) #desde el primero hasta el último (no incluido)
print(AlturaSalto[-3:]) #desde el antepenúltimo hasta el final

['Sujeto1', 0.23, 'Sujeto2', 0.38, 'Sujeto3']
[0.38, 'Sujeto3', 0.15]


También se puede seleccionar uno de cada tantos elementos. Se incluye un tercer número tras los dos puntos.

In [152]:
print(AlturaSalto[0:6:2])#del elemento 0 al 6 saltando de 2 en 2

['Sujeto1', 'Sujeto2', 'Sujeto3']


In [153]:
print(AlturaSalto[::2])#lo mismo que el anterior, del primero al último saltando de 2 en 2 (todos los pares)

['Sujeto1', 'Sujeto2', 'Sujeto3']


In [154]:
print(AlturaSalto[1:6:2])#del primero al último saltando de 2 en 2 pero empezando en el 1 (impares)

[0.23, 0.38, 0.15]


In [155]:
print(AlturaSalto[2:6:3])#del 2 al 6 saltando de 3 en 3...

['Sujeto2', 0.15]


Incluso se pueden mostrar hacia atrás:

In [156]:
print(AlturaSalto[::-1])#todos los elementos en orden inverso
print(AlturaSalto[::-2])#todos los elementos en orden inverso saltando de 2 en 2

[0.15, 'Sujeto3', 0.38, 'Sujeto2', 0.23, 'Sujeto1']
[0.15, 0.38, 0.23]


También se pueden hacer listas de listas:

In [157]:
AlturasSalto=[['Sujeto1', 0.23], ['Sujeto2', 0.38], ['Sujeto3', 0.15]]
print(AlturasSalto)

[['Sujeto1', 0.23], ['Sujeto2', 0.38], ['Sujeto3', 0.15]]


En este caso la lista tiene dos dimensiones (filas y columnas).
Para acceder a los elementos hay que indicar primero el número de filas y después el de columnas.

In [158]:
print(AlturasSalto[0])#esta es la primera fila completa

['Sujeto1', 0.23]


In [159]:
print(AlturasSalto[1][1])#esto es la fila cero, columna 1

0.38


En ocasiones no sabemos cuántos elementos va a tener una lista, sino que vamos a ir añadiendo sobre la marcha.
Por ejemplo al analizar datos, vamos calculando variables y almacenándolas en una lista

In [160]:
resultados=[]
resultados.append(0.23)
resultados.append(0.46)
resultados.append(0.32)
print(resultados)

[0.23, 0.46, 0.32]


## Tipo de variable básico para tratar datos en python: el módulo NUMPY

Se parecen a las listas pero pueden hacer muchas más cosas.

In [161]:
import numpy as np #forma de importar la librería.
x=np.array([1,4,5,7,3])
x

array([1, 4, 5, 7, 3])

También se puede iniciar a partir de una lista

In [162]:
alturas=[1.67, 1.76, 1.85, 1.79, 1.74]
npAlturas=np.array(alturas)
npAlturas

array([ 1.67,  1.76,  1.85,  1.79,  1.74])

Funcionan como las listas en la indexación:

In [163]:
print(alturas[0], npAlturas[0])
print(alturas[-1], npAlturas[-1])
print(alturas[1:3], npAlturas[1:3])
print(alturas[2:], npAlturas[2:])
print(alturas[2:-1], npAlturas[2:-1])
print(alturas[-3:], npAlturas[-3:])
print(alturas[:-3], npAlturas[:-3])
print(alturas[::-1], npAlturas[::-1])

1.67 1.67
1.74 1.74
[1.76, 1.85] [ 1.76  1.85]
[1.85, 1.79, 1.74] [ 1.85  1.79  1.74]
[1.85, 1.79] [ 1.85  1.79]
[1.85, 1.79, 1.74] [ 1.85  1.79  1.74]
[1.67, 1.76] [ 1.67  1.76]
[1.74, 1.79, 1.85, 1.76, 1.67] [ 1.74  1.79  1.85  1.76  1.67]


Pero hay diferencias importantes entre las listas y los numpy:

La lista está hecha de objetos que no son considerados números, no se pueden operar matemáticamente

In [164]:
print(alturas*2) #concatena
print(alturas+2) #error

[1.67, 1.76, 1.85, 1.79, 1.74, 1.67, 1.76, 1.85, 1.79, 1.74]


TypeError: can only concatenate list (not "int") to list

En cambio los numpy son números y se pueden operar uno a uno

In [165]:
print(npAlturas*2)
print(npAlturas+2)
print(npAlturas**2)

[ 3.34  3.52  3.7   3.58  3.48]
[ 3.67  3.76  3.85  3.79  3.74]
[ 2.7889  3.0976  3.4225  3.2041  3.0276]


Se puede operar entre numpys. Opera dato a dato en el mismo orden. Tienen que tener el mismo número de datos.

In [166]:
npPesos=np.array([92, 65, 73, 85, 58])

In [167]:
BMI=npPesos/npAlturas**2
print(BMI)

[ 32.98791638  20.9839876   21.32943755  26.52851035  19.15708812]


En numpy también se pueden hacer arrays de varias dimensiones:

In [168]:
#alturas y masas de 5 sujetos
datos=np.array([[1.67, 1.76, 1.85, 1.79, 1.74],
                  [92, 65, 73, 85, 58]])

Y se accede a cada elemento o grupo de elementos así:

In [169]:
print(datos[0, 2])#un solo elemento(fila, columna)
print(datos[0, :])#toda la fila 0 (alturas)
print(datos[:, 2])#toda la columna del sujeto 3º
print(datos[:, 2:4])#toda la columna del sujeto 3º

1.85
[ 1.67  1.76  1.85  1.79  1.74]
[  1.85  73.  ]
[[  1.85   1.79]
 [ 73.    85.  ]]


Podemos hacer la misma operación que antes dentro del mismo numpy

In [170]:
BMI2=datos[1, :] / datos[0, :]**2
print(BMI2)

[ 32.98791638  20.9839876   21.32943755  26.52851035  19.15708812]


Y también podemos hacer operaciones estadísticas:

In [171]:
print('promedio alturas: ', datos[0, :].mean())
print('promedio masas: ', datos[1, :].mean())

promedio alturas:  1.762
promedio masas:  74.6


### Operaciones para seleccionar datos que cumplan una condición

In [172]:
z=np.array([3,5,4,7,9,2,5,7,6,3,4,9,6])
zz = z[z>=7]
print(zz)
zz = z[z==7]
print(zz)
zz = z[z<4]
print(zz)
zz = z[z==z.max()]
print(zz)

zz = z[(z>3) & (z<7)]#para poner varias condiciones, meterlas entre paréntesis
print(zz)

zz = z[(z<3) | (z>7)] # los que sean menor que 3 y mayor que 7 
print(zz)

[7 9 7 9]
[7 7]
[3 2 3]
[9 9]
[5 4 5 6 4 6]


#### También se puede obtener el índice de los datos de la condición (orden dentro de la lista)

In [173]:
z=np.array([3,5,4,7,9,2,5,7,6,3,4,9,6])
iz = np.where(z>=7)
print(iz)
iz = np.where(z==7)
print(iz)
iz = np.where(z<4)
print(iz)
iz = np.where(z==z.max())
print(iz)

iz = np.where((z>3) & (z<7))#para poner varias condiciones, meterlas entre paréntesis
print(iz)

(array([ 3,  4,  7, 11], dtype=int64),)
(array([3, 7], dtype=int64),)
(array([0, 5, 9], dtype=int64),)
(array([ 4, 11], dtype=int64),)
(array([ 1,  2,  6,  8, 10, 12], dtype=int64),)


### Con numpy se pueden crear series de números, por ejemplo para variables de tiempo.
#### Si interesa controlar el intervalo entre datos
np.arange(nºinicial, nº final, intervalo):

In [174]:
t=np.arange(0, 10)
t

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [175]:
t=np.arange(0, -10, -1)#cuenta atrás
t

array([ 0, -1, -2, -3, -4, -5, -6, -7, -8, -9])

In [176]:
t=np.arange(0, 10, 0.05)
t

array([ 0.  ,  0.05,  0.1 ,  0.15,  0.2 ,  0.25,  0.3 ,  0.35,  0.4 ,
        0.45,  0.5 ,  0.55,  0.6 ,  0.65,  0.7 ,  0.75,  0.8 ,  0.85,
        0.9 ,  0.95,  1.  ,  1.05,  1.1 ,  1.15,  1.2 ,  1.25,  1.3 ,
        1.35,  1.4 ,  1.45,  1.5 ,  1.55,  1.6 ,  1.65,  1.7 ,  1.75,
        1.8 ,  1.85,  1.9 ,  1.95,  2.  ,  2.05,  2.1 ,  2.15,  2.2 ,
        2.25,  2.3 ,  2.35,  2.4 ,  2.45,  2.5 ,  2.55,  2.6 ,  2.65,
        2.7 ,  2.75,  2.8 ,  2.85,  2.9 ,  2.95,  3.  ,  3.05,  3.1 ,
        3.15,  3.2 ,  3.25,  3.3 ,  3.35,  3.4 ,  3.45,  3.5 ,  3.55,
        3.6 ,  3.65,  3.7 ,  3.75,  3.8 ,  3.85,  3.9 ,  3.95,  4.  ,
        4.05,  4.1 ,  4.15,  4.2 ,  4.25,  4.3 ,  4.35,  4.4 ,  4.45,
        4.5 ,  4.55,  4.6 ,  4.65,  4.7 ,  4.75,  4.8 ,  4.85,  4.9 ,
        4.95,  5.  ,  5.05,  5.1 ,  5.15,  5.2 ,  5.25,  5.3 ,  5.35,
        5.4 ,  5.45,  5.5 ,  5.55,  5.6 ,  5.65,  5.7 ,  5.75,  5.8 ,
        5.85,  5.9 ,  5.95,  6.  ,  6.05,  6.1 ,  6.15,  6.2 ,  6.25,
        6.3 ,  6.35,

#### Si interesa controlar el número de datos en el intervalo:

In [177]:
t= np.linspace(0, 10, 5)
t

array([  0. ,   2.5,   5. ,   7.5,  10. ])

In [178]:
t= np.linspace(0, -10, 10)
t

array([  0.        ,  -1.11111111,  -2.22222222,  -3.33333333,
        -4.44444444,  -5.55555556,  -6.66666667,  -7.77777778,
        -8.88888889, -10.        ])

### Se pueden iniciar numpys con un nº de dimensiones conocidas de distintas formas:

#### Vacío

In [179]:
x=np.empty([2,3])#2 filas y 3 columnas vacías
print(x)

[[  1.18515073e-311   1.18515002e-311   1.18515173e-311]
 [  1.18515073e-311   1.18515174e-311   1.18514983e-311]]


#### con algún valor concreto

In [180]:
x=np.zeros([2,3])#2 filas y 3 columnas vacías
print(x)
x=np.ones([2,3])#2 filas y 3 columnas vacías
print(x)
x=np.full([2,3], np.pi)#2 filas y 3 columnas vacías
print(x)


[[ 0.  0.  0.]
 [ 0.  0.  0.]]
[[ 1.  1.  1.]
 [ 1.  1.  1.]]
[[ 3.14159265  3.14159265  3.14159265]
 [ 3.14159265  3.14159265  3.14159265]]


#### con números aleatorios

In [181]:
yi=np.random.randint(0,10, size=(2, 3))#enteros entre el 0 y el 10, con 2 filas y 3 columnas
print(yi)

[[7 6 5]
 [7 2 7]]


In [182]:
y= np.random.rand(2, 3) #float entre 0 y 1. 2 filas y 3 columnas
print(y)

[[ 0.77709823  0.143607    0.08320264]
 [ 0.39921861  0.79696225  0.19167574]]


In [183]:
yn= np.random.randn(2, 3) #con distribución normal con media 0 y sd 1
print(yn)

[[-0.76544537  0.97742897 -1.64175665]
 [-1.39908551 -0.55733231  0.20697248]]


In [184]:
media=3.4
sd=0.5
ynn = np.random.normal(media, sd, [2, 3])#con distribución normal con media y sd definidas
print(ynn)

[[ 3.55793609  2.99815676  2.56763084]
 [ 2.94727739  3.47899272  3.4092705 ]]


In [185]:
opciones=['A','B','C','D','E']
seleccion=np.random.choice(opciones, size=4)
print('Selección con reemplazo ', seleccion)

seleccion=np.random.choice(opciones, size=4, replace=False)
print('Selección sin reemplazo ', seleccion)

seleccion=np.random.choice(opciones, size=(4,3), p=[0.6, 0.05, 0.15, 0.1, 0.1])
print('Selección con reemplazo y ajuste de probabilidades\n', seleccion)

Selección con reemplazo  ['D' 'D' 'B' 'C']
Selección sin reemplazo  ['D' 'E' 'C' 'B']
Selección con reemplazo y ajuste de probabilidades
 [['C' 'A' 'D']
 ['A' 'C' 'A']
 ['A' 'A' 'A']
 ['A' 'A' 'C']]


Se pueden visualizar rápidamente los datos.

In [186]:
import matplotlib.pyplot as plt
%matplotlib inline  

means=[1.9, 0.7,-1.5]
sigmas=[0.5, 1.3, 2.1]
sx = np.random.normal(means, sigmas, [30, len(means)])
plt.plot(sx,'o')
#plt.plot(sx[:, 0], 'bo')
#plt.plot(sx[:, 1], 'ro')

### Algunas operaciones para gestionar numpys

In [187]:
np.random.seed(1) #fija la aleatoriedad para que sea reproducible
a=np.random.randint(0,10, size=(2, 3))
b=np.random.randint(0,10, size=(2, 3))
c=np.vstack((a,b))#los une por debajo
print('a=', a, '\nb=', b, '\nc=', c, '\nDimensiones=', c.shape)

a= [[5 8 9]
 [5 0 0]] 
b= [[1 7 6]
 [9 2 4]] 
c= [[5 8 9]
 [5 0 0]
 [1 7 6]
 [9 2 4]] 
Dimensiones= (4, 3)


In [188]:
c=np.hstack((a,b))#los une poniendo uno al lado del otro
print('a=', a, '\nb=', b, '\nc=', c, '\nDimensiones=', c.shape)

a= [[5 8 9]
 [5 0 0]] 
b= [[1 7 6]
 [9 2 4]] 
c= [[5 8 9 1 7 6]
 [5 0 0 9 2 4]] 
Dimensiones= (2, 6)


In [189]:
d=c.T#transpone los datos, filas en columnas y al revés
print(d)

[[5 5]
 [8 0]
 [9 0]
 [1 9]
 [7 2]
 [6 4]]


## Otro tipo de variable complementario del numpy: PANDAS

Muy útil para gestionar bases de datos. Utilizan etiquetas de filas y columnas.
En series temporales normalmente las columnas representan variables y las filas los instantes temporales.

In [190]:
import pandas as pd

df=pd.DataFrame([3,5,6,2], columns=['var1'])
df2=pd.DataFrame(np.random.randint(0, 10, size=(4, 3)), columns=['a', 'b', 'c'])#se pueden nombrar las columnas directamente
print('df2= \n', df2)
#o cambiar la columnas por separado
df2.columns=['A', 'B', 'C']
print('df2= \n', df2)

df2= 
    a  b  c
0  5  2  4
1  2  4  7
2  7  9  1
3  7  0  6
df2= 
    A  B  C
0  5  2  4
1  2  4  7
2  7  9  1
3  7  0  6


Para describir rápidamente el dataframe

In [191]:
df=pd.DataFrame(np.random.rand(20, 3))
df.head()#presenta las 5 primeras filas

0         1         2
0  0.800745  0.968262  0.313424
1  0.692323  0.876389  0.894607
2  0.085044  0.039055  0.169830
3  0.878143  0.098347  0.421108
4  0.957890  0.533165  0.691877

In [192]:
df.tail()#presenta las 5 últimas filas

0         1         2
15  0.535896  0.663795  0.514889
16  0.944595  0.586555  0.903402
17  0.137475  0.139276  0.807391
18  0.397677  0.165354  0.927509
19  0.347766  0.750812  0.725998

In [193]:
df.describe()#estadísticas descriptivas

0          1          2
count  20.000000  20.000000  20.000000
mean    0.475478   0.455371   0.566987
std     0.316322   0.285713   0.323072
min     0.018288   0.039055   0.049953
25%     0.233529   0.160698   0.287975
50%     0.466787   0.469733   0.640591
75%     0.711860   0.680752   0.849621
max     0.957890   0.968262   0.988861

### Al copiar dataframes hay que tener cuidado, por defecto no hace una copia, sino que con otro nombre apunta a los mismos datos:

In [194]:
df2copia=df2#no crea una nueva copia de df2, solo podemos usar df2copia para nombrar el mismo df2
df2copia.columns=['a', 'b', 'c']#realmente ha cambiado df2
print('df2= \n', df2)

df2= 
    a  b  c
0  5  2  4
1  2  4  7
2  7  9  1
3  7  0  6


Para hacer una copia independiente hay que especificarlo.

In [195]:
df3=df2.copy() #df3 es una copia independiente
df3.columns=['A', 'B', 'C']#si le cambiamos algo, no afecta a df2
print('\ndf3= \n', df3)
print('\ndf2 no cambia= \n', df2)


df3= 
    A  B  C
0  5  2  4
1  2  4  7
2  7  9  1
3  7  0  6

df2 no cambia= 
    a  b  c
0  5  2  4
1  2  4  7
2  7  9  1
3  7  0  6


In [196]:
df3.index=['suj1', 'suj2', 'suj3', 'suj4']#los nombres de las filas también se pueden modificar
print('\ndf3= \n', df3)


df3= 
       A  B  C
suj1  5  2  4
suj2  2  4  7
suj3  7  9  1
suj4  7  0  6


### Se pueden seleccionar bloques de datos

In [197]:
df2[2:4]#todas las columnas, filas de 2 a 4 (no inclusive)

a  b  c
2  7  9  1
3  7  0  6

In [198]:
df2['a']#la columna 'a'

0    5
1    2
2    7
3    7
Name: a, dtype: int32

In [199]:
df2['a'][2:4]

2    7
3    7
Name: a, dtype: int32

In [200]:
df2[['a','c']]#para seleccionar varias columnas no consecutivas, incluirlas en otro corchete

a  c
0  5  4
1  2  7
2  7  1
3  7  6

In [201]:
df2.iloc[2:4, 1:3]#para seleccionar filas y columnas por bloques

b  c
2  9  1
3  0  6

In [202]:
df2['d']=df2['c']*2#crea una nueva columna
df2

a  b  c   d
0  5  2  4   8
1  2  4  7  14
2  7  9  1   2
3  7  0  6  12

In [203]:
df2['Sexo']=[0,1,1,0]#añade otra columna
df2

a  b  c   d  Sexo
0  5  2  4   8     0
1  2  4  7  14     1
2  7  9  1   2     1
3  7  0  6  12     0

In [204]:
print(df2.columns) #nombre de todas las columnas
print(df2.columns[-1]) #nombre de la última columna
print('El índice de la columna sexo es', df2.columns.get_loc('Sexo'))

Index(['a', 'b', 'c', 'd', 'Sexo'], dtype='object')
Sexo
El índice de la columna sexo es 4


### Se puede hacer referencia a un valor de distintas formas. Depende de si es más práctico usar el índice de las filas y columnas o su etiqueta:

In [205]:
print(df2['a'][1])#nombre de etiqueta de la columa y la fila
print(df2[df2.columns[0]][1])#número del nombre de la columna de la columa y fila
print(df2.loc[1,'a']) #con etiquetas, primero se indica la fila y después la columna
print(df2.iloc[1,0]) #con índices, primero se indica la fila y después la columna
print(df2.iloc[1,df2.columns.get_loc('a')]) #lo mismo que la anterior pero para cuando sabemos el nombre de la columna y no el índice
print(df2.iat[1,0]) #primero se indica la fila y después la columna
print(df2.at[1,'a']) #primero se indica la fila y después la columna

2
2
2
2
2
2
2


In [206]:
print('df3= \n', df3)
print(df3['B']['suj3'])#nombre de etiqueta de la columa y la fila
print(df3[df3.columns[1]]['suj3'])#número del nombre de la columna de la columa y fila
print(df3.loc['suj3','B']) #con etiquetas, primero se indica la fila y después la columna
print(df3.iloc[2,1]) #con índices, primero se indica la fila y después la columna
print(df3.iloc[1,df3.columns.get_loc('B')]) #lo mismo que la anterior pero para cuando sabemos el nombre de la columna y no el índice
print(df3.at['suj3','B']) #con etiquetas, primero se indica la fila y después la columna
print(df3.iat[2,1]) #con índices, primero se indica la fila y después la columna

df3= 
       A  B  C
suj1  5  2  4
suj2  2  4  7
suj3  7  9  1
suj4  7  0  6
9
9
9
9
4
9
9


Para modificar valores en una celda concreta. iat y at son más rápidos pero solo permiten modificar una celda, mientras que iloc y loc pueden hacerlo con más de una

In [207]:
df2.at[1, 'd']=11 #con etiquetas, modifica un valor por nombre fila, col
df2.iat[0, 2]=11 #con índices, modifica un valor por nº fila, col

df2.loc[1, 'd']=11 
df2.iloc[0, 2]=11 #con índices, modifica un valor por nº fila, col
df2.iloc[0:2, 2]=11 #se puede usar con selección de varias celdas a la vez.
df2.loc[1:2, 'nuevaCol']='nuevo' #loc e iloc también se pueden usar para crear nuevas filas o columnas
df2.loc[5, 'nuevaCol2']='nuevo'
print(df2)

     a    b     c     d  Sexo nuevaCol nuevaCol2
0  5.0  2.0  11.0   8.0   0.0      NaN       NaN
1  2.0  4.0  11.0  11.0   1.0    nuevo       NaN
2  7.0  9.0   1.0   2.0   1.0    nuevo       NaN
3  7.0  0.0   6.0  12.0   0.0      NaN       NaN
5  NaN  NaN   NaN   NaN   NaN      NaN     nuevo


In [208]:
df2[['a','b']]=df2[['a','b']].astype(np.float)#cambiar el tipo de datos de las columnas
df2

a    b     c     d  Sexo nuevaCol nuevaCol2
0  5.0  2.0  11.0   8.0   0.0      NaN       NaN
1  2.0  4.0  11.0  11.0   1.0    nuevo       NaN
2  7.0  9.0   1.0   2.0   1.0    nuevo       NaN
3  7.0  0.0   6.0  12.0   0.0      NaN       NaN
5  NaN  NaN   NaN   NaN   NaN      NaN     nuevo

### Se pueden selecionar filas según los datos cumplan una o varias condiciones. 

In [209]:
chicos=df2[df2['Sexo']==0]#selecciona las filas según los valores de una variable
chicos

a    b     c     d  Sexo nuevaCol nuevaCol2
0  5.0  2.0  11.0   8.0   0.0      NaN       NaN
3  7.0  0.0   6.0  12.0   0.0      NaN       NaN

In [210]:
chicos=df2[(df2['Sexo']==0) & (df2['c']>=5) | (df2['a']< 2)]#selecciona las filas según más de una condición
chicos

a    b     c     d  Sexo nuevaCol nuevaCol2
0  5.0  2.0  11.0   8.0   0.0      NaN       NaN
3  7.0  0.0   6.0  12.0   0.0      NaN       NaN

In [211]:
df2.columns #nombres de las columnas

Index(['a', 'b', 'c', 'd', 'Sexo', 'nuevaCol', 'nuevaCol2'], dtype='object')

In [212]:
df3=df2.drop('c', axis=1) #elimina columnas enteras. Para que lo haga en la misma variable df2.drop('c', axis=1, implace=True)
df3

a    b     d  Sexo nuevaCol nuevaCol2
0  5.0  2.0   8.0   0.0      NaN       NaN
1  2.0  4.0  11.0   1.0    nuevo       NaN
2  7.0  9.0   2.0   1.0    nuevo       NaN
3  7.0  0.0  12.0   0.0      NaN       NaN
5  NaN  NaN   NaN   NaN      NaN     nuevo

### Se pueden reordenar las columnas

In [213]:
#Orden alfabético
variables=['G', 'A', 'b', 'C', 'E', 'a', 'H']
dfOrden=pd.DataFrame(np.random.rand(10, len(variables)), columns=variables)
dfOrden.sort_index(axis=1, inplace=True)
print(dfOrden.columns)

Index(['A', 'C', 'E', 'G', 'H', 'a', 'b'], dtype='object')


### Reordenar columnas especificando el orden

In [214]:
dfOrden=dfOrden.reindex (columns=['H', 'E', 'a', 'A', 'C', 'G', 'b'])
print(dfOrden.columns)

Index(['H', 'E', 'a', 'A', 'C', 'G', 'b'], dtype='object')


### Para cambiar el nombre de alguna columna

In [215]:
variables=['G', 'A', 'b', 'C', 'E', 'a', 'H']
dfOrden=pd.DataFrame(np.random.rand(10, len(variables)), columns=variables)
#dfOrden.replace(['b', 'a'], ['BB', 'AA'])
dfOrden.rename(columns={'b':'BB', 'a':'AA'}, inplace=True)

print(dfOrden.columns)

Index(['G', 'A', 'BB', 'C', 'E', 'AA', 'H'], dtype='object')


### Para seleccionar columnas por grupos con alguna coincidencia en el nombre

In [216]:
variables=['A_marcha_CA', 'B_marcha_CA', 'VI_marcha_CA', 'A_marcha_BR', 'B_marcha_BR', 'VI_marcha_BR', 'A_marcha_MA', 'B_marcha_MA', 'VI_marcha_MA', 'A_carrera_CA', 'B_carrera_CA', 'VI_carrera_CA', 'A_carrera_BR', 'B_carrera_BR', 'VI_carrera_BR', 'A_carrera_MA', 'B_carrera_MA', 'VI_carrera_MA']
dfLargo=pd.DataFrame(np.random.rand(10, len(variables)), columns=variables)
dfA=dfLargo.filter(regex='A_marcha') #mete en un mismo df todas las variables que contienen 'A_marcha'
print(dfA.columns)

dfCarrera=dfLargo.filter(regex='_carrera_') #mete en un mismo df todas las variables sobre carrera
print(dfCarrera.columns)

Index(['A_marcha_CA', 'A_marcha_BR', 'A_marcha_MA'], dtype='object')
Index(['A_carrera_CA', 'B_carrera_CA', 'VI_carrera_CA', 'A_carrera_BR',
       'B_carrera_BR', 'VI_carrera_BR', 'A_carrera_MA', 'B_carrera_MA',
       'VI_carrera_MA'],
      dtype='object')


### Para sustituir valores en columnas. Por ejemplo, si tenemos la columna Sexo con 1 y 0 y queremos cambiarlo a 'Hombres' 'Mujeres'

In [217]:
dfCambioValores=pd.DataFrame({'Sexo':[1,1,0,0,1,0,1,1,0,0,1]})
print(dfCambioValores)
dfCambioValores.replace([0, 1], ['Hombre', 'Mujer'], inplace=True)
print(dfCambioValores)

    Sexo
0      1
1      1
2      0
3      0
4      1
5      0
6      1
7      1
8      0
9      0
10     1
      Sexo
0    Mujer
1    Mujer
2   Hombre
3   Hombre
4    Mujer
5   Hombre
6    Mujer
7    Mujer
8   Hombre
9   Hombre
10   Mujer


### Cuenta el nº de veces que se repite cada valor en una columna.
útil para variables categóricas

In [218]:
#Cuenta el nº de veces que se repite cada valor en una columna.
#útil para variables categóricas
numSexo=dfCambioValores['Sexo'].value_counts()
print(numSexo)

Mujer     6
Hombre    5
Name: Sexo, dtype: int64
